name: garage_sale_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ^0.15.7
  image_picker:
  cloud_firestore:
  firebase_core:
  firebase_auth: ^0.15.5+3
  firebase_database:
  firebase_storage:
  dio: 1.0.0
  google_fonts: ^0.4.0
  flutter_local_notifications:
  geolocator: ^5.1.3
  google_maps_flutter: ^0.5.11
  location: ^2.3.5
  modal_progress_hud: ^0.1.3
  multi_image_picker:
  mlkit:
  firebase_ml_vision: ^0.9.3+8
  url_launcher: ^5.4.2
  font_awesome_flutter: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/